/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ms;
import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.util.*;

/**
 *
 * @author jburt
 */
public class minesweeperFrame extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form minesweeperFrame
     */
    
    
    
    private SquareMinesweeperGame testGame;
    private JButton[][] grid;
    public minesweeperFrame() {
        initComponents();
        setSize(600, 600);
        
        testGame = new SquareMinesweeperGame(10, 10);
        grid = drawButtonGrid(10);
                
        testGame.addObserver(this);                        
    }
    
    private JButton[][] drawButtonGrid(int gridSize){
        this.setLayout(new GridLayout(gridSize, gridSize));
        
        JButton[][] grid = new JButton[gridSize][gridSize];
        for (int y = 0; y < gridSize; y++){
            for (int x = 0; x < gridSize; x++){
                JButton button = new JButton(); 
                this.add(button);
                button.setText("#");
                button.addActionListener(new ClickHandler(x, y, testGame));
                grid[y][x] = button;
            }
        }
        return grid;
    }
    
    public void update(Observable obj, Object arg){
        // game has been updated
        // retrieve the updated grid
        // update the view accordingly
        for(int y = 0; y < 10; y++){
            for (int x = 0; x < 10; x++){
                if (grid[y][x]!=null){
                    SquareMinesweeperTile tile = testGame.tileAtCoord(x, y);
                    if (!tile.isRevealed()){
                        // set to #
                        grid[y][x].setText("#");
                    } else {
                        if (tile.isBomb()){
                            // set to B
                            grid[y][x].setText("B");
                        } else {
                            // set to adjacent bomb count
                            grid[y][x].setText(Integer.toString(tile.adjacentBombs()));
                        }
                    }
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minesweeper");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(minesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(minesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(minesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(minesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new minesweeperFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
